### ISSUE TITLE
Tomatoes public API

### ISSUE THREAD

**Issue by potomak** [potomak/tomatoes#15]
## TODO list

- [x] Remove ResourceController (#162)
- [x] API documentation
  - [x] Reference manual
- [x] Add API namespace and base controller (#163)
  - [x] Find user by Tomatoes token
    - [x] Add `authorizations.token` index to `users`
- [x] `API::SessionsController`
  - [x] POST /session
    - [x] Login with GitHub
    - [x] Login with Twitter (#186)
  - [x] DESTROY /session
- [x] `API::TomatoesController`
  - [x] GET /tomatoes
  - [x] GET /tomatoes/:id
  - [x] POST /tomatoes
  - [x] PATCH /tomatoes/:id
  - [x] DESTROY /tomatoes/:id
- [x] `API::UsersController`
  - [x] GET /user
  - [x] PATCH /user
- [x] `API::ProjectsController`
  - [x] GET /projects
  - [x] GET /projects/:id
  - [x] POST /projects
  - [x] PATCH /projects/:id
  - [x] DESTROY /projects/:id
- [x] Add new `User` index, run `User.create_indexes` on a production console

**Comment by potomak** [comment]
Action plan:

* Remove `ResourceController` https://github.com/potomak/tomatoes/issues/162
* Add API namespace and base controller https://github.com/potomak/tomatoes/issues/163
* `API::SessionController`
  * POST /session
  * DESTROY /session
* `API::TomatoesController`
  * GET /tomatoes
  * GET /tomatoes/:id
  * POST /tomatoes
  * PATCH /tomatoes/:id
  * DESTROY /tomatoes/:id
* `API::UserController` or `API::ProfileController`
  * GET /user
  * PATCH /user
* `API::ProjectsController`
  * GET /projects
  * GET /projects/:id
  * POST /projects
  * PATCH /projects/:id
  * DESTROY /projects/:id

**Comment by pablosproject** [comment]
👍 ping me once done I can help with the iPhone client

**Comment by potomak** [comment]
I created a new project to collect all the tasks to get this done: https://github.com/potomak/tomatoes/projects/2.

**Comment by pablosproject** [comment]
What's the status of this? Can I start doing some query to the API? Or at least have an example of the JSON model, I can start preparing the mobile app.

**Comment by potomak** [comment]
@pablosproject I plan on release a new version of Tomatoes that includes the API by the end of this week. There's an issue with the Twitter auth implementation and it can be used only with Tomatoes client id and secret, I'll open a new issue to fix the issue in a later version.

**Comment by potomak** [comment]
@pablosproject Tomatoes 0.9.0 is online. It includes an early version of the API. Take a look at the reference documentation at http://www.tomato.es/pages/api_reference and tell me if I can help.

**Comment by potomak** [comment]
@bugant from a security point of view this API should be used only through HTTPS, I guess I'll add a new issue to keep track of the progress on it.

**Comment by pablosproject** [comment]
@potomak it'll ne useful to create a new issue to keep track of the iOS app, and a new repo to store the code of it.

**Comment by potomak** [comment]
@pablosproject start a new project using your account, I will create a new organization to collect all projects related to Tomatoes in the near future.

**Comment by pablosproject** [comment]
Nice. I suggest also creating a gitter for the project, just to avoid chit chatting in issues.

**Comment by potomak** [comment]
I registered a [#tomatoes](irc://irc.freenode.net/tomatoes) channel more than 2 years ago at http://freenode.net/ that could be used to chat about the project:

```
Information on #tomatoes:
Founder    : potomak
Successor  : freenode-staff
Registered : Jun 24 13:57:29 2014 (2y 16w 4d ago)
```

I will add info about the channel on the README soon.

**Comment by pablosproject** [comment]
I suggest not using IRC since we're working on different timezones and you don't have the history saved with it. Gitter or Slack are better approach IMHO.

**Comment by potomak** [comment]
@pablosproject please open a new issue to start a conversation on the chat topic. Let's stay on the API topic here.
