### ISSUE TITLE
Leaderboards v2

### ISSUE THREAD

**Issue by potomak** [potomak/tomatoes#206]
The new leaderboard documents will be stored in four separate collections:

* `daily_scores`
* `weekly_scores`
* `monthly_scores`
* `overall_scores`

Documents in these collection will include:

* `uid` (alias `user_id`), reference to `user._id`
* `s` (alias `score`), integer
* `eat` (alias `expires_at`), datetime
* `cat` (alias `created_at`), datetime
* `uat` (alias `updated_at`), datetime

Each collection will include the indexes:

* `{ uid: 1 }` (the order is irrelevant)
* `{ s: -1 }`
* `{ eat: 1 }, { expireAfterSeconds: 0 }` (to set the correct TTL for each document)

Note: `overall_scores` won't include neither the `eat` attribute nor the TTL index because overall scores don't expire.

An example query to populate the daily leaderboard page would be:

```javascript
db.daily_scores.sort({ s: -1 })
```

Note: the query would be timezone independent because documents would expire according to their TTL, that depends on the associated user's timezone.

## An alternative approach (using a single collection)

The alternative approach is to store leaderboard documents in a single collection `scores`.

Documents in this new collection will include:

* `uid` (alias `user_id`), reference to `user._id`
* `ds` (alias `daily_score`), integer
* `ws` (alias `weekly_score`), integer
* `os` (alias `overall_score`), integer
* `cat` (alias `created_at`), datetime
* `uat` (alias `updated_at`), datetime

An example query to populate the daily leaderboard page (EST timezone, -4:00) would be:

```javascript
db.scores.find({ uat: { $gte: new ISODate("2016-11-29T04:00:00Z") } }).sort({ ds: -1 })
```

The issue with this approach is that it's hard to find a good index for the query. A composite index `{ uat: 1, ds: -1 }` would include a *sort stage* to sort the subset of documents selected by the `find` condition. A composite index `{ ds: -1, uat: 1 }` would prevent sorting the results, but it would need to scan the index to filter out documents based on the `find` condition. Finally a partial index would not work because the index condition should be dynamic, based on date and timezone.

## Async operations

Score collections documents should be created/updated asynchronously by sucker-punch workers. There's already an open PR (https://github.com/potomak/tomatoes/pull/199) started by @bugant, that put the foundations to use workers to update records in the old leaderboard collections.

A `ScoreUpdaterJob` worker should take care of updating score documents. The worker takes two parameters: a user id, a score delta. It creates/updates the correct score document in each of the four collections. New documents should have a TTL according to their leaderboard period and user's timezone, i.e. daily: beginning of the next day, weekly: beginning of the next week, monthly: beginning of the next month.

## Naming

The old code mixes three different concepts: *leaderboard*, *score*, and *ranking*.

*Ranking* is used in the wrong way. A user's ranking should be his/her position in a leaderboard. At the moment we're not going to show the ranking anywhere.

*Score* is the former `value` attribute of leaderboard document. Score is a more appropriate term. In Tomatoes leaderboards context, the score represents the number of tomatoes completed by a user from the beginning of a period. There are four possible periods:

1. *daily*, from the beginning of the current day
1. *weekly*, from the beginning of the current week
1. *monthly*, from the beginning of the current month
1. *overall*, from the moment the user has been created

*Leaderboard* is a list of score documents ordered by descending score value. There are four different leaderboards, one for each period. Note: these lists should be paginated.

## TODO

- [ ] Create new score models
  - [ ] `DailyScore` model
  - [ ] `WeeklyScore` model
  - [ ] `MonthlyScore` model
  - [ ] `OverallScore` model
- [ ] `ScoreUpdaterJob` (https://github.com/potomak/tomatoes/pull/199)
- [ ] update `Tomato` to perform asynchronously `ScoreUpdaterJob`
  - [ ] `after_create` (delta: +1)
  - [ ] `after_destroy` (delta: -1)
- [ ] Migrate score data to the new collections
- [ ] Create new leaderboards controllers
  The old controller is called `RankingsController`, let's create a new controller `LeaderboardsController`
  - [ ] GET `/daily`
  - [ ] GET `/weekly`
  - [ ] GET `/monthly`
  - [ ] GET `/overall`
- [ ] API endpoints
  - [ ] GET `/daily`
  - [ ] GET `/weekly`
  - [ ] GET `/monthly`
  - [ ] GET `/overall`

## References

* http://openmymind.net/2011/5/8/Practical-NoSQL-Solving-a-Real-Problem-w-Mongo-Red/
* https://emptysqua.re/blog/optimizing-mongodb-compound-indexes/
* https://docs.mongodb.com/manual/core/index-compound/
* https://docs.mongodb.com/manual/tutorial/expire-data/
* https://docs.mongodb.com/v3.2/tutorial/sort-results-with-indexes/
* https://docs.mongodb.com/v3.2/tutorial/analyze-query-plan/
* https://docs.mongodb.com/v3.2/reference/explain-results/

**Comment by potomak** [comment]
I migrated users overall score by running the script:

```ruby
User.all.limit(2000).skip(0).map do |user|
  begin
    tomatoes_count = user.tomatoes.count
    next unless tomatoes_count > 0
    print "User: #{user._id} (#{user.name}), score: #{tomatoes_count}... "

    user_score = OverallScore.where(uid: user._id).first
    if user_score.nil?
      puts 'Creating new score'
      OverallScore.create!(uid: user._id, score: tomatoes_count)
      next
    end

    puts 'Update existing score'
    user_score.update!(score: tomatoes_count)
  rescue => e
    puts "Error: #{e}"
  end
end; nil
```
